### ISSUE TITLE
关于节点个数以及预处理文件的问题

### ISSUE THREAD

**Issue by su-zelong** [slingling/HG-SL#2]
请问为什么您的代码中用户节点数量与您提到的https://github.com/safe-graph/GNN-FakeNews工作中的节点数量不同呢？例如在politifact数据集中，您的代码中总结点个数是28050（用户节点数）+314（新闻节点数），而链接中的节点个数为40740（用户节点数）+314（新闻节点数）；另外可以分享一下 user_centered_data.txt 和 news_centered_data.txt 这两个文件的来源或者处理方法吗？期待您的回复，祝科研顺利

**Comment by slingling** [comment]
你说的这个问题我也研究过，我觉得是他们的文章里面每个图是独立的，也就是说应该是统计了重复的用户，但是我是直接列出了所有用户，每个是unique的。这两个文件是我根据https://github.com/mdepak/fake-news-propagation项目的原始数据，分别以用户为主和以新闻为主统计的交互信息。

**Comment by su-zelong** [comment]
很高兴收到您的回复，正如您说的，确实是针对每个新闻有独立的图导致了用户标签的重复，但是事实上数据集中的不重复用户数是30812，新闻数是314，用户节点数还是有出入。您是有筛掉边缘用户或者对新闻树剪枝类似的操作吗？
